context.properties = {
    # up to 32 different sample rates may be specified (must be supported by sink device)
    default.clock.allowed-rates = [ 44100 48000 88200 96000 176400 192000 352800 384000 768000 ]
}

node.rules = [
    {
        matches = [
            # match playback streams for supersonic
            {
                # prefer ALSA or PulseAudio for supersonic because native pipewire streams
                # have a bug where it attaches to input drivers when suspended,
                # forcing the wrong rate on the input driver, leading to 44.1 kHz
                # mic streams
                node.name = "alsa_playback.supersonic-desktop"
            }
            {
                node.name = "supersonic"
            }
        ]
        actions = {
            update-props = {
                # force the sample rate in `node.rate` denominator on the graph, despite the graph being active
                node.force-rate = 0
                # # if the resampler is disabled entirely,
                # # the node will only be able to negotiate with the graph when the samplerates are compatible
                # resample.disable = true
                # # prefill resampler buffers with silence (this is a debug option)
                # resample.prefill = true
            }
        }
    }
]
