#! /bin/sh

bspc rule -r "*"

bspc monitor DP-0 -d 1 2 3 4
bspc monitor DP-2 -d 5 6 7 8

bspc config split_ratio 0.50
bspc config borderless_monocle false
# bspc config gapless_monocle false

bspc config gapless_monocle true

# bspc config pointer_modifier lock
# bspc config pointer_action1 move
# bspc config pointer_action2 resize_side
# bspc config pointer_action3 resize_corner

bspc config merge_overlapping_monitors

bspc rule -a thunderbird desktop="^2"
bspc rule -a discord desktop="^3"
bspc rule -a vesktop desktop="^3"
bspc rule -a steam desktop="^1"

bspc config ignore_ewmh_focus true

bspc config normal_border_color	"#595959"
bspc config active_border_color	"#595959"
bspc config focused_border_color "#33ccff"
bspc config presel_feedback_color "#595959"

bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 6

nvidia-settings --load-config-only
pactl set-default-source alsa_input.usb-Soundcraft_Notepad-5-00.analog-stereo
pactl set-default-sink alsa_output.usb-DIDI_AUDIO_TC100COA-01.analog-stereo

alacritty --daemon &

pgrep -x thunderbird >/dev/null 2>&1 || thunderbird &
pgrep -x vesktop >/dev/null 2>&1 || vesktop &

(pkill -USR1 -x sxhkd || true) &

eww close-all && eww open-many xbar:primary xbar:secondary --arg primary:screen=0 --arg secondary:screen=1
