#!/bin/sh

query() {
    (bspc query -D -d focused --names || echo "99")
    bspc query --names -M | while read -r m; do (bspc query --names -D -d "$m":focused || echo "99"); done
}

refresh() {
    # ["d",{"d":bool,...}]
    query | tr "\n" " " | \
        awk '{printf "[\"%s\",{", $1; for(i=2;i<NF;i++) printf "\"%s\":true,", $i; printf "\"%s\":true}]\n", $NF}'
}

refresh

bspc subscribe desktop_focus | while read -r _; do
    refresh
done
