#!/usr/bin/env bash
# credit: https://github.com/ThePrimeagen/.dotfiles

set -e

if ! command -v fzf &> /dev/null; then
    echo Error: Fzf not installed!
    exit 1
fi

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find -L ~/Sync -mindepth 1 -maxdepth 1 -type d -not -name ".*" | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
if [[ -z $TMUX ]] && ! pgrep tmux &> /dev/null; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if ! tmux has-session -t "$selected_name" 2> /dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t "$selected_name"
    exit 0
fi

tmux switch-client -t "$selected_name"

# vim: ft=bash
