#!/bin/sh

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

riverctl map normal Control+Alt Delete spawn \
    "${XDG_CONFIG_HOME}/river/quit"  # important

"${XDG_CONFIG_HOME}/river/keybinds" &
"${XDG_CONFIG_HOME}/river/ruleset" &

riverctl input "pointer-*" accel-profile none

riverctl keyboard-layout us
riverctl set-repeat 32 225

# allow vsync to be disabled if requested by view
riverctl allow-tearing enabled

riverctl declare-mode passthrough
riverctl declare-mode gamemode

riverctl set-cursor-warp on-output-change

riverctl border-color-focused 0x33ccff
riverctl border-color-unfocused 0x595959

riverctl default-attach-mode bottom

riverctl default-layout bsp-layout
timestamp="$(date +%F-%R)"
WAYLAND_DEBUG=1 river-bsp-layout \
    --inner-gap 3 \
    --outer-gap 6 \
    --split-perc 0.5 > /tmp/river-bsp-layout."${timestamp}".log 2>&1 &

# The user dbus session is shared across all login sessions and all ttys
# Therefore, only tell it about the first wayland session
if [ "$WAYLAND_DISPLAY" = "wayland-1" ]; then
    dbus-update-activation-environment --systemd WAYLAND_DISPLAY \
        XDG_CURRENT_DESKTOP DISPLAY QT_QPA_PLATFORMTHEME PATH
    systemctl --user is-active xdg-desktop-portal.service \
        && systemctl --user restart xdg-desktop-portal.service
fi

# workaround for wayland clipboard -> wine-xwayland sharing (extremely buggy)
# wl-paste -t text -w xclip -selection clipboard &

## logind must have a "graphical" session in order to correctly interpret idle events from wayland
##   see: reddit.com/r/swaywm/comments/e8jk1o/-/fad68o7/
# swayidle -w lock 'sudo -K; waylock -fork-on-lock' idlehint 60 &

thunar --daemon &
foot -C || echo "error: foot config check failed" >&2
foot -s &
eww daemon

timestamp="$(date +%F-%R)"
kanshi > /tmp/kanshi."${timestamp}".log 2>&1 &

swaybg -i ~/Pictures/Wallpapers/duo_light.jpg -m fill &
