#!/bin/sh

riverctl map normal Super+Shift R spawn \
    '"$XDG_CONFIG_HOME/river/keybinds" \
        || "$HOME/.config/river/keybinds"; \
        "$XDG_CONFIG_HOME/river/ruleset" \
            || "$HOME/.config/river/ruleset"; \
        notify-send "river: Reloaded keybinds and ruleset"'

# launch programs
riverctl map normal Super B spawn firefox
riverctl map normal Super Return spawn "alacritty msg create-window"
riverctl map normal Super Tab spawn "tofi-run | xargs riverctl spawn"

## screenshots
# fullscreen
riverctl map normal None Print spawn 'mkdir -p "$(xdg-user-dir PICTURES)/Screenshots"; grim -o "$(river-bedload -print outputs | jq -r ".[] | select(.focused) | .name")" - | tee -p "$(xdg-user-dir PICTURES)/Screenshots/$(date +%Y-%m-%d_%s.png)" | wl-copy && notify-send "Screenshot saved"'

# selection (no freezing frame!)
riverctl map normal Shift Print spawn 'mkdir -p "$(xdg-user-dir PICTURES)/Screenshots"; grim -g "$(slurp)" - | tee -p "$(xdg-user-dir PICTURES)/Screenshots/$(date +%Y-%m-%d_%s.png)" | wl-copy && notify-send "Screenshot saved"'

# lock the screen (spawn waylock)
riverctl map normal Control+Alt L spawn waylock

## Vim key split controls
riverctl map normal Super H focus-view left
riverctl map normal Super J focus-view down
riverctl map normal Super K focus-view up
riverctl map normal Super L focus-view right

riverctl map normal Super+Shift H swap left
riverctl map normal Super+Shift J swap down
riverctl map normal Super+Shift K swap up
riverctl map normal Super+Shift L swap right

# emoji script
riverctl map normal Super Period spawn "echo emoji_placeholder | tofi --fuzzy true"

# # Super+Period and Super+Comma to focus the next/previous output
# riverctl map normal Super Period focus-output next
# riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
# riverctl map normal Super+Shift Period send-to-output next
# riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
#riverctl map normal Super Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
# riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
# riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
# riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
# riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
# riverctl map normal Super+Alt H move left 100
# riverctl map normal Super+Alt J move down 100
# riverctl map normal Super+Alt K move up 100
# riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
# riverctl map normal Super+Alt+Control H snap left
# riverctl map normal Super+Alt+Control J snap down
# riverctl map normal Super+Alt+Control K snap up
# riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
# riverctl map normal Super+Alt+Shift H resize horizontal -100
# riverctl map normal Super+Alt+Shift J resize vertical 100
# riverctl map normal Super+Alt+Shift K resize vertical -100
# riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# for i in $(seq 1 9)
# do
#     tags=$((1 << ($i - 1)))
#
#     riverctl map normal Super $i set-focused-tags $tags
#     riverctl map normal Super+Shift $i set-view-tags $tags
# done

# # Super+0 to focus all tags
# # Super+Shift+0 to tag focused view with all tags
# all_tags=$(((1 << 32) - 1))
# riverctl map normal Super 0 set-focused-tags $all_tags
# riverctl map normal Super+Shift 0 set-view-tags $all_tags

# # Super+Space to toggle float
# riverctl map normal Super Space toggle-float

riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
# riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
# riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
# riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
# riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

riverctl map normal Super Q close
# riverctl map normal Control+Alt Delete exit

riverctl map normal Control+Alt Delete spawn \
    'notify-send "river: Quitting"; \
        "$XDG_CONFIG_HOME/river/quit" \
        || "$HOME/.config/river/quit"'
