#!/bin/sh

riverctl map normal Super+Shift R spawn \
    '"$XDG_CONFIG_HOME/river/keybinds" \
        || "$HOME/.config/river/keybinds"; \
        "$XDG_CONFIG_HOME/river/ruleset" \
            || "$HOME/.config/river/ruleset"; \
        notify-send "river: Reloaded keybinds and ruleset"'

# launch programs
riverctl map normal Super B spawn firefox
riverctl map normal None XF86HomePage spawn firefox
riverctl map normal None XF86WWW spawn firefox
riverctl map normal Super Return spawn footclient
riverctl map normal Super Tab spawn 'tofi-run --output="$(river-bedload -minified -print outputs | jq -rcM --unbuffered ".[] | select(.focused == true) | .name")" | xargs riverctl spawn'
riverctl map normal Super E spawn Thunar

## screenshots
# fullscreen
riverctl map normal None Print spawn 'mkdir -p "$(xdg-user-dir PICTURES)/Screenshots"; grim -o "$(river-bedload -print outputs | jq -r ".[] | select(.focused) | .name")" - | tee -p "$(xdg-user-dir PICTURES)/Screenshots/$(date +%Y-%m-%d_%s.png)" | wl-copy && notify-send "Screenshot saved"'

# selection (no freezing frame!)
riverctl map normal Shift Print spawn 'mkdir -p "$(xdg-user-dir PICTURES)/Screenshots"; grim -g "$(slurp)" - | tee -p "$(xdg-user-dir PICTURES)/Screenshots/$(date +%Y-%m-%d_%s.png)" | wl-copy && notify-send "Screenshot saved"'

# lock the screen
riverctl map normal Control+Alt L spawn 'sudo -K; waylock'

## Vim key split controls
riverctl map normal Super H focus-view left
riverctl map normal Super J focus-view down
riverctl map normal Super K focus-view up
riverctl map normal Super L focus-view right

riverctl map normal Super+Shift H swap left
riverctl map normal Super+Shift J swap down
riverctl map normal Super+Shift K swap up
riverctl map normal Super+Shift L swap right

# emoji script
riverctl map normal Super Period spawn "echo emoji_placeholder | tofi --fuzzy true"

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# # Super+Space to toggle float
# riverctl map normal Super Space toggle-float

riverctl map gamemode Control+Alt G spawn "$XDG_CONFIG_HOME/river/scripts/ungamemode"
riverctl map normal Control+Alt G spawn "$XDG_CONFIG_HOME/river/scripts/gamemode DP-3"

riverctl map normal Super F toggle-fullscreen

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

riverctl map normal Super Q close

## media keys
MEDIAPLAYER="${MEDIAPLAYER:-Supersonic}"
for mode in normal locked; do
    riverctl map "$mode" Super Left spawn "playerctl -s -p $MEDIAPLAYER position 6-"
    riverctl map "$mode" Super Right spawn "playerctl -s -p $MEDIAPLAYER position 5+"

    riverctl map "$mode" None XF86AudioPlay spawn "playerctl -s -p $MEDIAPLAYER play-pause"
    riverctl map "$mode" None XF86AudioPrev spawn "playerctl -s -p $MEDIAPLAYER previous"
    riverctl map "$mode" None XF86AudioNext spawn "playerctl -s -p $MEDIAPLAYER next"
    riverctl map "$mode" None XF86AudioStop spawn "playerctl -s -p $MEDIAPLAYER stop"
    #riverctl map "$mode" None XF86AudioMute spawn "playerctl -s -p $MEDIAPLAYER volume 0.0"
    riverctl map "$mode" None XF86AudioLowerVolume spawn "playerctl -s -p $MEDIAPLAYER volume 0.1-"
    riverctl map "$mode" None XF86AudioRaiseVolume spawn "playerctl -s -p $MEDIAPLAYER volume 0.1+"

    riverctl map "$mode" Super Down spawn "playerctl -s -p $MEDIAPLAYER volume 0.1-"
    riverctl map "$mode" Super Up spawn "playerctl -s -p $MEDIAPLAYER volume 0.1+"
done
