#!/bin/sh

pgrep -x steam > /dev/null 2>&1 && \
    steam steam://exit

eww kill 2> /dev/null

extra_time=0
pgrep -x vesktop > /dev/null 2>&1 && \
    extra_time=1

# kill x processess that do not exit on window close
# waits for term before continuing
terminate_bg vesktop \
    bitwarden \
    eww \
    caffeine \
    polkit-gnome-authentication-agent-1 \
    firefox \
    obsidian \
    zotero \
    thunderbird

# wait for any desktop processes that are still running
parallel --timeout 20 \
    "pgrep -x '{}' > /dev/null 2>&1 || exit; pidwait '{}'" ::: steam

sleep "$extra_time"

# kills any autostart programs launched with bspwmrc
riverctl exit
