#!/bin/sh


## note: get wayland application IDs using `lswt`

# enforce server side decorations by default
riverctl rule-add -app-id "*" ssd

# necessary for drawing split borders
# riverctl rule-add -app-id "firefox" ssd
# riverctl rule-add -app-id "steam" ssd
# riverctl rule-add -app-id Thunar ssd
# riverctl rule-add -app-id mpv ssd

# disable compositor vsync for Steam games running via proton
riverctl rule-add -app-id "steam_app_*" tearing

# spawn Steam games on tag 1
riverctl rule-add -app-id "steam_app_*" tags 1

# not working for some reason
riverctl rule-add -app-id firefox -title "Page Info —*" float
