#!/bin/sh

# enforce server side decorations by default
riverctl rule-add -app-id "*" ssd

# necessary for drawing split borders
# riverctl rule-add -app-id "firefox" ssd
# riverctl rule-add -app-id "steam" ssd
# riverctl rule-add -app-id Thunar ssd
# riverctl rule-add -app-id mpv ssd

# disable compositor vsync for Steam games running via proton
riverctl rule-add -app-id "steam_app_*" tearing

# spawn Steam games on tag 1
riverctl rule-add -app-id "steam_app_*" tags 1

riverctl rule-add -app-id eu4 fullscreen
riverctl rule-add -app-id eu4 tearing
riverctl rule-add -app-id eu4 tags 1

# currently not possible to match against firefox title, as all windows are created
# with a default title and rules only apply to new views
riverctl rule-add -app-id Zotero -title "Zotero Settings" float
riverctl rule-add -app-id xdg-desktop-portal-gtk -title "Select cover image" float
riverctl rule-add -app-id thunar float
riverctl rule-add -app-id thunar -title "* - Thunar" no-float  # main window
riverctl rule-add -app-id "Peak Meter" float  # main window

riverctl rule-add -app-id com.obsproject.Studio -title Stats float
