#!/bin/sh

# display configuration
#   see: ~/.config/kanshi/config

if [ $# -gt 9 ]; then
    echo "ERR: number of outputs cannot exceed 9" >&2
    exit 1
fi

if [ $# -eq 0 ]; then
    echo "ERR: must specify at least 1 output" >&2
    exit 1
fi

conf() {
    # shellcheck disable=SC2046
    IFS= set -- $(cat)

    n=$(echo "$# / 2" | bc)
    step=$(echo "9 / $n" | bc)
    while [ $# -ge 2 ]; do
        i=$1
        shift
        name=$1
        shift
        hi=$(echo "$i * $step" | bc)
        lo=$(echo "$hi - ($step - 1)" | bc)


        river-mon "$name" "$lo" "$hi"
    done
}

i=0
conf <<EOF
$(for arg in "$@"; do
    i=$((i + 1))
    for output in ${WELLKNOWN_OUTPUTS:-"DP-1"}; do
        if [ "$arg" != "$output" ]; then
            continue
        fi
        echo "$i $arg"
        continue 2
    done
    echo "arg: $arg is not well-known - skipping" >&2
done)
EOF

# spawn Steam games on primary monitor
riverctl rule-add -app-id "steam_app_*" output "$1"

# primary must be set for clicks to register for some XWayland programs
xrandr --output "$1" --primary
