# negotiate per-session RGB and 256-color terminal support
set -g default-terminal "tmux"
set -g update-environment "DISPLAY SSH_ASKPASS SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY TERM"
if "[[ ${TERM} =~ 256color || ${TERM} == fbterm ]]" "set -g default-terminal tmux-256color"
if "[[ ${COLORTERM} == truecolor ]]" "set -sg terminal-overrides ',*:RGB'"

# begin capturing all mouse input
set -g mouse on

# enable underscore style based on terminal support
if "[[ ${TERM} == alacritty || ${TERM} == kitty || ${TERM} == foot || ${TERM} == st-256color ]]" "set-option -ga terminal-features ',*:usstyle'"

# reset mouse cursor shape using OSC 22 (if supported)
if "[[ ${TERM} == foot || ${TERM} == kitty ]]" {
    set -g allow-passthrough on
    run-shell 'printf "\033Ptmux;\033\033]22;\033\033\\033\\"'
}

set -g prefix C-a
bind C-a send-prefix
unbind C-b

# ~5-100 - delay in ms for fragmented escape sequences across read/packet boundries
set -s escape-time 5

# numbering for panes and windows
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g status-style "bg=#333333 fg=#afafaf"
set -g status-right "#{=21:host_short}"
set -g status-right-length 40
set -g status-left "[#{=21:session_name}]"
set -g status-left-length 23

set -g pane-border-style "fg=#afafaf"
set -g pane-active-border-style "bg=default fg=#afafaf"

set -g set-titles on
set -g set-titles-string "tmux: #T"

bind R {
    source-file "$HOME/.config/tmux/tmux.conf"
    display-message "Reloaded tmux config."
}

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

set -g focus-events on

unbind -T copy-mode MouseDown1Pane
unbind -T copy-mode MouseDrag1Pane
unbind -T copy-mode MouseDragEnd1Pane
unbind -T copy-mode-vi MouseDown1Pane
unbind -T copy-mode-vi MouseDrag1Pane
unbind -T copy-mode-vi MouseDragEnd1Pane
unbind -n MouseDown1Pane
unbind -n MouseDown2Pane
unbind -n MouseDown3Pane
unbind -n MouseDrag1Pane
unbind -n M-MouseDown3Pane
unbind -n DoubleClick1Pane
unbind -n TripleClick1Pane

set -g history-limit 50000
setw -g aggressive-resize on
