# ALSA node property overrides

# info logging
# context.properties = { log.level = "I" }

monitor.alsa.rules = [
    # disable audio devices
    {
        matches = [
            {
                # Navi 48 HDMI/DP Audio Controller
                device.name = "alsa_card.pci-0000_03_00.1"
            }
            {
                # ASUS Generic USB Audio
                device.name = "alsa_card.usb-Generic_USB_Audio-00"
            }
            {
                # HD Pro Webcam C920
                # this will not disable the pipewire video device
                device.name = "alsa_card.usb-046d_HD_Pro_Webcam_C920_A492956F-02"
            }
        ]
        actions = {
            update-props = {
                device.disabled = true
            }
        }
    }
    # disable node for sink provided from audio interface
    {
        matches = [
            {
                # Notepad-5 Analog Stereo
                # this will not disable the ALSA source node
                node.name = "~alsa_output.usb-Soundcraft_Notepad-5-00.*"
            }
        ]
        actions = {
            update-props = {
                node.disabled = true
            }
        }
    }
    # configure device for default sink
    {
        matches = [
            {
                device.name = "alsa_card.usb-SMSL_SMSL_USB_AUDIO-00"
            }
        ]
        actions = {
            update-props = {
                device.profile = "pro-audio"
            }
        }
    }
    # configure node for default sink
    {
        matches = [
            {
                # SMSL SU-1
                node.name = "~alsa_output.usb-SMSL_SMSL_USB_AUDIO-00.*"
            }
        ]
        actions = {
            update-props = {
                # prevent auto-suspend of existing devices on idle (increases power usage)
                session.suspend-timeout-seconds = 0

                # prevents missed samples from the beginning of playback due to rate switching
                #   note: only applied when ALSA device is (re)-created, device is usually only
                #   re-created when switching rate or after suspension
                # https://pipewire.pages.freedesktop.org/wireplumber/daemon/configuration/alsa.html#startup-tweaks
                api.alsa.start-delay = 65536  # value in samples (not relative to sample rate)
            }
        }
    }
]

wireplumber.settings = {
  device.restore-profile = true
  device.restore-routes = true
  device.routes.default-sink-volume = 1.0
  device.routes.default-source-volume = 1.0
  node.stream.restore-props = true
  node.stream.restore-target = true
  node.stream.default-playback-volume = 1.0
  node.stream.default-capture-volume = 1.0
  node.restore-default-targets = true
}
